version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: db
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    image: image_share
    build: .
    restart: always
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./site/media/
        target: /var/www/media/

volumes:
  pgdata:
