version: '3'

services:
  server:
    image: image_share
    build: .
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./db.sqlite3
        target: /srv/db.sqlite3
      - type: bind
        source: ./media/media/
        target: /var/www/media/