version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    image: image_share
    build: .
    restart: always
    environment:
      SECRET_KEY: ${SECRET_KEY}
      PGSERVICEFILE: ${PGSERVICEFILE}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
      PYTHONPATH: ${PYTHONPATH}
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./site/media/
        target: /var/www/media/

volumes:
  pgdata:
