# Generated by Django 4.1.7 on 2023-03-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='image',
        ),
        migrations.AddField(
            model_name='tag',
            name='images',
            field=models.ManyToManyField(to='imageapp.image'),
        ),
    ]
