# Generated by Django 4.1.7 on 2023-03-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0002_remove_tag_image_tag_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='images',
            field=models.ManyToManyField(blank=True, to='imageapp.image'),
        ),
    ]
