# Generated by Django 4.1.7 on 2023-03-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0003_alter_tag_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
        migrations.AlterField(
            model_name='image',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ManyToManyField(to='imageapp.image'),
        ),
    ]
