# Generated by Django 4.1.7 on 2023-03-27 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0005_remove_comment_image_comment_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='user',
            new_name='owner',
        ),
    ]
