# Generated by Django 4.1.7 on 2023-04-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0009_alter_image_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
