# Generated by Django 4.1.7 on 2023-04-13 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0010_alter_image_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imageapp.profile'),
        ),
        migrations.AlterField(
            model_name='image',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imageapp.profile'),
        ),
        migrations.AlterField(
            model_name='report',
            name='byUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='by_user', to='imageapp.profile'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reportedUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_user', to='imageapp.profile'),
        ),
    ]
