# Generated by Django 4.1.7 on 2023-04-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0012_alter_comment_owner_alter_image_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(upload_to='profile_picture'),
        ),
    ]
